### ISSUE TITLE
Alternative uppercase C

### ISSUE THREAD

**Issue by Crissov** [playbeing/dinish#12]
Dinish Condensed Bold is being used in the new [CSS logo](https://github.com/CSS-Next/logo.css/issues/14) for the uppercase letter sequence “CSS”. The lower terminal in the opening of the C ends higher up than the lower terminal of the S. The logo would look more harmonic if they were on the same virtual horizontal line. While this could be changed easily within a graphic, it would be preferable if it existed as a stylistic variant or contextual alternative, so authors could recreate it simply with CSS.

**Comment by driehuis** [comment]
I see the problem... Thanks for making a case for it!

This is where the original design comes back to haunt me. For new glyphs, I have religiously made them match shapes with existing ones, but I have steered clear so far of really butchering the original glyphs for the sake of orthogonality (mostly because the deviations from DIN 1451 are what makes DINish work as a daily driver).

I think a stylistic variant for use at larger point sizes is called for. If I were a glutton for punishment I could even consider an optical size axis in the upcoming VF...

Thanks for pointing this out, I have added this to the todo list!

**Comment by rol4nd909** [comment]
I see it's also with the top terminals. I hope it will be in the next release so we can finalize the logo. 

I see it's also with the top terminals. I hope it will be in the next release so we can [finalize the logo](https://github.com/CSS-Next/logo.css/pull/35).

**Comment by driehuis** [comment]
The glyphs were originally designed for body text, and aligning the terminals wasn't a priority (I wasn't there when that was done, but the evidence bears it out).

I noticed that you trimmed the straight part of the terminal of the "C", rather than adding a straight part to the terminal of the "S". That flies in the face of everyting the Deutsche Normung stands for, so I went the opposite direction.

I have reviewed what he change would look like at smaller point sizes and found it to be still pleasing, at least in the bold and the regular.
![Screenshot at 2024-12-17 14-05-30](https://github.com/user-attachments/assets/d08704b2-f5e0-4f39-9bff-ee0edd4a3e56)
 Would this work for you?

**Comment by Crissov** [comment]
Works for me, but I’m hardly involved. Better ask @chriskirknielsen et al.

**Comment by rol4nd909** [comment]
This looks awesome, is it also the same for condensed heavy variant? That is the one we use in the logo?

**Comment by driehuis** [comment]
The heavy is derived from the regular and the bold by interpolation. I need to tweak all the masters to make the entire family consistent, and that means that I'm going through the iterative process of refining it and fixing the fallout. I will pay extra attention to reviewing the 800 condensed before releasing 4.002, which will include the fixes. Stuff may shift half a pixel at Retina resolution at the logo size I've seen in the linked issues, but I'll include a rendering at 800 condensed in this ticket when it's ready.

Turning DINish into a variable font has been an interesting journey, and it has uncovered a ton of skeletons in the closet. It's constructive criticism like this that really helps push the envelope, so bear with me while I clean things up.

**Comment by driehuis** [comment]
Here's the condensed 800 DINishCondensed heavy as I intend to release it.

Thi screenshot was generated from the variable font in Firefox:
![Screenshot at 2024-12-18 00-34-52](https://github.com/user-attachments/assets/057735ac-efab-4950-b509-e9e4febd6200)

The screenshot was generated from the static instance DINishCondensed-Heavy in libreOffice:
![Screenshot at 2024-12-18 00-49-47](https://github.com/user-attachments/assets/6d20709b-44e3-4cb5-90c1-3510b492ecba)
(I know the scaling if off, I couldn't quickly find a way to get libreOffice and Firefox to agree on a height in pixels and I didn't want to fix it up in GIMP as that would require scaling, which open up a can of worms in itself).

I'm totally stoked that the variable font holds up so well in the first place!

**Comment by rol4nd909** [comment]
Thanks for the hard work, it looks perfect in my opinion.

I'll wait for the release, after that I'll update the logo!

**Comment by driehuis** [comment]
DINish v4.002 is out with these fixes included. If you're using the variable font, you may wish to wait for v4.003, which will see the 'Regular' dropped from it's name internally. This only affects projects that use introspection, which is probably a small minority, but it does affect our specimen page so I'm quite motivated to fix it.

**Comment by chriskirknielsen** [comment]
Thanks for the tag @Crissov!

This is fantastic, thank you for your hard work @driehuis!
Also I wasn't aware of the rules of trimming vs extending the terminal for this type style… the more you know! Thank you so much. 😄
